<a href="https://colab.research.google.com/github/SheikhCham/Exam/blob/main/vectors1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
v=np.array([1,-1,2])
w=np.array([2,5,2])

In [6]:
print(v+w)
print(v-w)

[3 4 4]
[-1 -6  0]


In [8]:
#ScalarMultiplication
print(3*v)
print(3*w)

[ 3 -3  6]
[ 6 15  6]


In [10]:
print(np.linalg.norm(v))

2.449489742783178
