<a href="https://colab.research.google.com/github/SheikhCham/Exam/blob/main/Vectors2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
P=np.array([[1,7],[2,1],[3,2]])
print(P)

[[1 7]
 [2 1]
 [3 2]]


In [15]:
Q=np.array([[1,1],[1,-1],[1,1]])
print(Q)

[[ 1  1]
 [ 1 -1]
 [ 1  1]]


In [16]:
C1=np.add(P,Q)
print(C1)

[[2 8]
 [3 0]
 [4 3]]


In [18]:
R=np.array([[1,3,1],[1,0,1]])
print(R)

[[1 3 1]
 [1 0 1]]


In [19]:
C2=np.dot(C1,R)
print(C2)

[[10  6 10]
 [ 3  9  3]
 [ 7 12  7]]


In [21]:
det=np.linalg.det(C2)

In [22]:
print(det)

-3.463895836830476e-14
